version: '3.4'

services:
  n5.microservices.user.api:
    image: ${DOCKER_REGISTRY-}n5microservicesuserapi
    build:
      context: .
      dockerfile: N5.Microservices.User.API/Dockerfile
    networks:
      - app-tier

  kafka:
    image: 'bitnami/kafka:latest'
    volumes:
    - /path/to/kafka-persistence:/bitnami/kafka
    networks:
      - app-tier

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - 1436:1436
    environment:
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y
    networks:
      - app-tier
  
  elastic:
    image: elasticsearch:latest
    ports:
    - 9300:9300
    environment:
      - discovery.type=single-node
    networks:
      - app-tier